In [333]:
import re
import nltk
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
english_stemmer=nltk.stem.SnowballStemmer('english')
from sklearn.feature_selection.univariate_selection import SelectKBest, chi2, f_classif
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import itertools
import os

In [334]:
df_news = pd.read_csv(r'C:\Users\Pavlina\Desktop\POC\Combined_News_DJIA.csv')

In [335]:
df_news.head()

Date  Label                                               Top1  \
0  2008-08-08      0  b"Georgia 'downs two Russian warplanes' as cou...   
1  2008-08-11      1  b'Why wont America and Nato help us? If they w...   
2  2008-08-12      0  b'Remember that adorable 9-year-old who sang a...   
3  2008-08-13      0  b' U.S. refuses Israel weapons to attack Iran:...   
4  2008-08-14      1  b'All the experts admit that we should legalis...   

                                                Top2  \
0            b'BREAKING: Musharraf to be impeached.'   
1        b'Bush puts foot down on Georgian conflict'   
2                 b"Russia 'ends Georgia operation'"   
3  b"When the president ordered to attack Tskhinv...   
4  b'War in South Osetia - 89 pictures made by a ...   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   
2  b'"If we had no sexual harassment we would hav...   
3  b' Israel clears troops who killed Reuters cam...   
4  b'Swedish wrestler Ara Abrahamian throws away ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   
2  b"Al-Qa'eda is losing support in Iraq because ...   
3  b'Britain\'s policy of being tough on drugs is...   
4  b'Russia exaggerated the death toll in South O...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   
2  b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3  b'Body of 14 year old found in trunk; Latest (...   
4  b'Missile That Killed 9 Inside Pakistan May Ha...   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   
2  b'Why Microsoft and Intel tried to kill the XO...   
3  b'China has moved 10 *million* quake survivors...   
4  b"Rushdie Condemns Random House's Refusal to P...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   
2  b'Stratfor: The Russo-Georgian War and the Bal...   
3  b"Bush announces Operation Get All Up In Russi...   
4  b'Poland and US agree to missle defense deal. ...   

                                                Top8  \
0  b"The 'enemy combatent' trials are nothing but...   
1  b'An American citizen living in S.Ossetia blam...   
2  b"I'm Trying to Get a Sense of This Whole Geor...   
3             b'Russian forces sink Georgian ships '   
4  b'Will the Russians conquer Tblisi? Bet on it,...   

                         ...                          \
0                        ...                           
1                        ...                           
2                        ...                           
3                        ...                           
4                        ...                           

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   
2  b'U.S. troops still in Georgia (did you know t...   
3                      b'Elephants extinct by 2020?'   
4  b'Bank analyst forecast Georgian crisis 2 days...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   
2       b'Why Russias response to Georgia was right'   
3  b'US humanitarian missions soon in Georgia - i...   
4  b"Georgia confict could set back Russia's US r...   

                                               Top18  \
0  b'Condoleezza Rice: "The US would not act to p...   
1  b'Riots are still going on in Montreal (Canada...   
2  b'Gorbachev accus

In [338]:
from textblob import TextBlob
import re

def clean(headline):
    
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", headline).split())

def sentiment(headline):
   
    analysis = TextBlob(clean(headline))
    if analysis.sentiment.polarity > 0:
        return 1
    elif analysis.sentiment.polarity == 0:
        return 0
    else:
        return -1

In [339]:
#Sentiment polarity using TextBlob
from textblob import TextBlob

def sentiment(headline):
   
    analysis = TextBlob(clean(headline))
    if analysis.sentiment.polarity > 0:
        return 1
    elif analysis.sentiment.polarity == 0:
        return 0
    else:
        return -1

In [340]:
topn_headlines = 20
top_num = range(1,topn_headlines+1)
dataframe_col = 'sum_sent' + str(max(top_num))
df_news[dataframe_col] = 0
for ii in top_num:
    read_col = 'Top' + str(ii)
    write_col = 'Top' + str(ii) + '_sent'
    df_news[write_col] = np.array([ sentiment(headline) for headline in df_news[read_col] ])
    df_news[dataframe_col] = df_news[dataframe_col] + df_news[write_col]
df_news

Date  Label                                               Top1  \
0     2008-08-08      0  b"Georgia 'downs two Russian warplanes' as cou...   
1     2008-08-11      1  b'Why wont America and Nato help us? If they w...   
2     2008-08-12      0  b'Remember that adorable 9-year-old who sang a...   
3     2008-08-13      0  b' U.S. refuses Israel weapons to attack Iran:...   
4     2008-08-14      1  b'All the experts admit that we should legalis...   
5     2008-08-15      1  b"Mom of missing gay man: Too bad he's not a 2...   
6     2008-08-18      0  b'In an Afghan prison, the majority of female ...   
7     2008-08-19      0  b"Man arrested and locked up for five hours af...   
8     2008-08-20      1  b'Two elderly Chinese women have been sentence...   
9     2008-08-21      1  b"British resident held in Guantanamo Bay wins...   
10    2008-08-22      1  b'Syria says its ready to put a Russian missil...   
11    2008-08-25      0  b"N Korea's Kim died in 2003; replaced by look...   
12    2008-08-26      1  b'North Korea halts denuclearisation after US ...   
13    2008-08-27      1  b'Photos of a 15-year-old Iraqi suicide bomber...   
14    2008-08-28      1  b"Military help for Georgia is a 'declaration ...   
15    2008-08-29      0  b'Russian Prime Minister Vladimir Putin has ac...   
16    2008-09-02      0  b"A girl filmed Israeli soldiers' brutality. S...   
17    2008-09-03      1  b'Poland Legalization of Marijuana - two majou...   
18    2008-09-04      0  b'Security guards beat man at soccer (football...   
19    2008-09-05      1  b'In Jordan, the honor killings that are not: ...   
20    2008-09-08      1  b'A French judge has ordered two branches of S...   
21    2008-09-09      0  b'I love the world: Thai Prime Minister Samak ...   
22    2008-09-10      1  b'Dutch to ban burkas when picking children up...   
23    2008-09-11      1  b'American intelligence confirms that the late...   
24    2008-09-12      0     b"OPEC finished??  Saudi Arabia says 'LATER!'"   
25    2008-09-15      0  b'Did Saakashvili Lie?: The West Begins to Dou...   
26    2008-09-16      1  b"Pakistani Tribesmen Representing Half A Mill...   
27    2008-09-17      0    b'Attack on US embassy in Yemen leaves 16 dead'   
28    2008-09-18      1      b'6,200 babies sick: Milk scandal spreading '   
29    2008-09-19      1  b'Brits take a stand - ban short-selling of fi...   
...          ...    ...                                                ...   
1959  2016-05-20      1  LinkedIn just revealed that the 2012 breach th...   
1960  2016-05-23      0  'It keeps happening,' rape survivor says: Prot...   
1961  2016-05-24      1  Colombia has fired more than 1000 police offic...   
1962  2016-05-25      1  Adidas shoe manufacture returns to Germany, fu...   
1963  2016-05-26      0  Greek news sites are reporting that Aristotle'...   
1964  2016-05-27      1  Thailand has shut down 10 popular diving sites...   
1965  2016-05-31      0  Every reference to the Great Barrier Reef remo...   
1966  2016-06-01      1  Forty tiger cub bodies have been found in a fr...   
1967  2016-06-02      1           Germany recognizes the Armenian Genocide   
1968  2016-06-03      0  A seven-year-old boy who went missing in bear-...   
1969  2016-06-06      1  Nearly 60% of Qatar population live in 'labour...   
1970  2016-06-07      1  Five Men in India Have Been Convicted for the ...   
1971  2016-06-08      1  UN Removes Saudi Arabia From Human Rights Blac...   
1972  2016-06-09      0  Vandals Destroy 8,000-Yr-Old Aboriginal Artwor...   
1973  2016-06-10      0  U.N. Chief Admits He Removed Saudi Arabia From...   
1974  2016-06-13      0  A Dutch woman who alleged she was raped after ...   
1975  2016-06-14      0  Gay Chinese man sues mental hospital for tryin...   
1976  2016-06-15      0  ISIS Twitter accounts have been hijacked with ...   
1977  2016-06-16      1  Decriminalisation Call As 'War On Drugs' Fails...   
1978  2016-06-17      0           

In [341]:
headlines_columns = range(1,21)
x_data_list = []
for rows in range(len(df_news)):
    x_dataTemp = []
    for i in range(1,21):
        x_dataTemp.append(df_news.loc[rows,'Top'+str(i)+'_sent'])
    x_data_list.append(x_dataTemp)
x_data = np.array(x_data_list)
y_label = df_news['Label']  

In [342]:
# Y value converted to categotical 
from keras.utils.np_utils import to_categorical
y_label = to_categorical(y_label)


In [343]:
#Array of average daily sentiment score
x_data2 = x_data
x_data2=np.mean(x_data2, axis=1)

In [344]:
# break the dataset to to 65% training and 35% test.
train_sample_perc = .65
n_samples = len(y_label)
x_train = x_data_list[:int(train_sample_perc * n_samples)]
y_train = y_label[:int(train_sample_perc * n_samples)]
x_test = x_data_list[int(train_sample_perc * n_samples):]
y_test = y_label[int(train_sample_perc * n_samples):]

In [345]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix 
from keras.models import Sequential, load_model
from keras.layers import LSTM, Dense, Dropout, Embedding
import os
import tensorflow as tf

In [346]:
def creat_my_dataset(df):
    x = []
    y = []
    for i in range(50,df.shape[0]):
        x.append(df[i-50:i,0])
        y.append(df[i,0])
    x = np.array(x)
    y = np.array(y)
    return x,y

In [347]:
#LSTM model

In [348]:
x_train=np.array(x_train)
y_train=np.array(y_train)
x_test=np.array(x_test)
y_test=np.array(y_test)

In [349]:
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1],1))
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1],1))
print(x_train.shape)
print(x_test.shape)

(1292, 20, 1)
(697, 20, 1)


In [350]:
tf.logging.set_verbosity(tf.logging.ERROR)
model = Sequential()
model.add(LSTM(units=96, return_sequences=True, input_shape=(x_train.shape[1],1)))
model.add(Dropout(0.2))
model.add(LSTM(units=96, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=96))
model.add(Dropout(0.2))
model.add(Dense(units=2, activation='softmax'))


In [351]:
model.compile(optimizer = 'adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [352]:
if (not os.path.exists(r'C:\Users\Pavlina\Desktop\LSTM\LSTM_Model_News_Sentiment_&_Stock_Movement3.h5')):
    model.fit(x_train, y_train, epochs=50, batch_size=32)
    model.save(r'C:\Users\Pavlina\Desktop\LSTM\LSTM_Model_News_Sentiment_&_Stock_Movement3.h5')

Epoch 1/50
1292/1292 [==============================] - 6s 4ms/step - loss: 0.6933 - acc: 0.5348A: 5s - loss: 0.6939 -
Epoch 2/50
1292/1292 [==============================] - 2s 1ms/step - loss: 0.6913 - acc: 0.5379
Epoch 3/50
1292/1292 [==============================] - 2s 1ms/step - loss: 0.6913 - acc: 0.5379
Epoch 4/50
1292/1292 [==============================] - 2s 1ms/step - loss: 0.6918 - acc: 0.5379
Epoch 5/50
1292/1292 [==============================] - 2s 1ms/step - loss: 0.6906 - acc: 0.5379
Epoch 6/50
1292/1292 [==============================] - 2s 1ms/step - loss: 0.6909 - acc: 0.5379
Epoch 7/50
1292/1292 [==============================] - 2s 1ms/step - loss: 0.6917 - acc: 0.5379
Epoch 8/50
1292/1292 [==============================] - 2s 1ms/step - loss: 0.6909 - acc: 0.5410
Epoch 9/50
1292/1292 [==============================] - 2s 1ms/step - loss: 0.6908 - acc: 0.5379
Epoch 10/50
1292/1292 [==============================] - 2s 1ms/step - loss: 0.6905 - acc: 0.5372
Epoch 1

In [353]:
result=model.evaluate(x_test,y_test)
print(result)

697/697 [==============================] - 1s 2ms/step
[0.6950807390117235, 0.5322812044808649]


In [354]:
#SVM model

In [355]:
X = x_data2
y = df_news['Label']

In [ ]:
y.valuescount

In [356]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.35) 

In [357]:
svm1 = SVC(kernel='linear',gamma=2)  
svm1.fit(X_train, y_train)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=2, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [358]:
y_pred = svm1.predict(X_test) 
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[  0 318]
 [  0 379]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       318
           1       0.54      1.00      0.70       379

   micro avg       0.54      0.54      0.54       697
   macro avg       0.27      0.50      0.35       697
weighted avg       0.30      0.54      0.38       697



C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [359]:
svm2 = SVC(kernel='poly', degree=8, gamma=2) 
svm2.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma=2, kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [360]:
y_pred2 = svm1.predict(X_test) 
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[  0 318]
 [  0 379]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       318
           1       0.54      1.00      0.70       379

   micro avg       0.54      0.54      0.54       697
   macro avg       0.27      0.50      0.35       697
weighted avg       0.30      0.54      0.38       697



C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [361]:
svm3 = SVC(kernel='sigmoid',gamma=2)
svm3.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=2, kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [362]:
y_pred3 = svm1.predict(X_test) 
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[  0 318]
 [  0 379]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       318
           1       0.54      1.00      0.70       379

   micro avg       0.54      0.54      0.54       697
   macro avg       0.27      0.50      0.35       697
weighted avg       0.30      0.54      0.38       697



C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [363]:
svm4 = SVC(kernel='rbf',gamma=2)
svm4.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=2, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [364]:
y_pred4 = svm1.predict(X_test) 
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[  0 318]
 [  0 379]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       318
           1       0.54      1.00      0.70       379

   micro avg       0.54      0.54      0.54       697
   macro avg       0.27      0.50      0.35       697
weighted avg       0.30      0.54      0.38       697



C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Pavlina\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
